# 一、ndarray
# 1.ndarray的特性
# 多维性

In [6]:
from email.policy import default
from random import random

import numpy as np
from numpy import dtypes
from numpy.lib import user_array
from numpy.ma.core import mean
from pip._internal.models import target_python

from 高阶函数.返回函数 import count

In [10]:
arr = np.array(5)
print(arr)
print('arr维度',arr.ndim)#数组的维度

5
arr维度 0


In [11]:
arr = np.array([1,2,3])
print(arr)
print('arr维度', arr.ndim)  #数组的维度

[1 2 3]
arr维度 1


In [12]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr = np.array([1,'hello'])#强制类型转换
print(arr)

['1' 'hello']


#2.ndarray的属性

In [14]:
arr = np.array(1)
print(arr)
print('数组形状：',arr.shape)

1
数组形状： ()


#3.ndarray的创建

In [19]:
#基础创建方法
list1 = [1,2,3]
list2 = [4,5,6]
arr = np.array(list1,dtype=np.float64)
print(arr.ndim)


1


In [22]:
arr1 = np.copy(arr)#元素跟原始的数组相同，但是不是一个数组了
print(arr1)
arr[0] = 10
print(arr)
arr2 = np.copy(arr)
print(arr2)

[1. 2. 3.]
[10.  2.  3.]
[10.  2.  3.]


In [24]:
#预定义形状
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)
print(arr.ndim)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
2


In [27]:
arr = np.empty((20,3))
print(arr)

[[2.88644025e+214 1.06758000e+224 1.10640016e+200]
 [6.04100990e+151 3.95053751e+252 1.53831922e+256]
 [3.99906146e+252 4.70106416e+180 5.75677440e+252]
 [2.46562122e-154 2.65575842e-260 5.54919955e+170]
 [5.26757278e+170 1.32908379e-258 1.33629952e-152]
 [4.35766483e-114 3.11067237e+161 8.82894586e+199]
 [2.44514188e-154 2.58276571e-144 6.01347002e-154]
 [1.79805224e+044 4.53685210e+217 6.51880092e+265]
 [7.49736832e+247 1.38772545e+219 1.21860238e-152]
 [2.49970344e+262 3.58251229e+246 4.70103241e+180]
 [2.87244898e+161 1.33856861e-152 9.46694601e+218]
 [1.27734658e-152 6.01346954e-154 6.01347002e-154]
 [6.20311190e+223 3.17095858e+180 4.71651679e+257]
 [3.55959720e+180 4.82407130e+228 2.42766862e-154]
 [6.01347002e-154 2.58415064e+161 2.32380474e+251]
 [2.35566768e+251 3.01633069e+161 8.02146756e+165]
 [2.35053208e+180 5.81543600e+180 6.01347002e-154]
 [8.06274510e+000 3.92391223e+252 2.16639291e-027]
 [8.78421503e+247 2.18174371e+243 1.74928933e+243]
 [9.75025264e+199 1.02188594e-1

In [29]:
arr = np.full((3,4),2025)
print(arr)

[[2025 2025 2025 2025]
 [2025 2025 2025 2025]
 [2025 2025 2025 2025]]


In [30]:
arr1 = np.zeros_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [32]:
arr = np.arange(2,11,2)
print(arr)

[ 2  4  6  8 10]


In [33]:
arr = np.linspace(1,51,6)
print(arr)

[ 1. 11. 21. 31. 41. 51.]


In [35]:
arr = np.logspace(0,5,5,base=10)
print(arr)

[1.00000000e+00 1.77827941e+01 3.16227766e+02 5.62341325e+03
 1.00000000e+05]


In [54]:
#特殊矩阵
#单位矩阵：主对角线上的数字为1，其他数字为0
arr = np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [46]:
#对角矩阵：主对角线上非0的数字，其他的数字为0
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [56]:
#特殊矩阵
#单位矩阵:主对角线上的数字为1，其他数字为0
arr = np.eye(3,dtype=int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [58]:
#随机数组
arr = np.random.rand(2,3)
print(arr)

[[0.00768754 0.80418815 0.61551775]
 [0.21097726 0.30878703 0.27775578]]


In [62]:
#生成指定范围区间的随机浮点数
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[5.68269554 5.56416601 4.85835366]
 [5.51966759 3.28775693 5.83401871]]


In [63]:
#生成指定范围区间的随机整数
arr = np.random.randint(3, 6, (2, 3))
print(arr)

[[4 4 4]
 [4 5 5]]


In [66]:
#生成正态分布随机数列
#两边的概率小，中间的概率大
arr = np.random.randn(2, 3)
print(arr)

[[ 1.58890932  0.84653543  0.82128333]
 [ 0.33460508 -1.19300261  0.63062374]]


In [74]:
#生成随机种子
np.random.seed(10)
arr = np.random.randint(1,100,(5,3))
print(arr)

[[10 16 65]
 [29 90 94]
 [30  9 74]
 [ 1 41 37]
 [17 12 55]]


#4.ndarray的数据类型

布尔类型 bool

整数类型 int

浮点数 float

复数 complex

In [77]:
arr = np.array([1,2,3],dtype='bool')
print(arr)

[ True  True  True]


In [84]:
arr = np.array([1, 2, 8,127], dtype=np.int8)
print(arr)
print(arr)

[  1   2   8 127]
[  1   2   8 127]


#5.索引与切片

In [88]:
#一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)
print(arr[1])

[78 89 16  7 86 23 12 13 93 97 63 58 80 43 58 98 51 46 41 90]
89


In [95]:
print(arr[:])#获取了全部的数据
print(arr[5:9])#左闭右开
print(arr[arr>10])

[78 89 16  7 86 23 12 13 93 97 63 58 80 43 58 98 51 46 41 90]
[23 12 13 93]
[78 89 16 86 23 12 13 93 97 63 58 80 43 58 98 51 46 41 90]


In [100]:
print(arr[(arr>10) & (arr<70)])
print(arr[slice(2,10,2)])

[16 23 12 13 63 58 43 58 51 46 41]
[16 86 12 93]


In [123]:
#二维数组的索引与切片
arr = np.random.randint(1,100,(5,3))
print(arr)
print(arr[0,2])
print(arr[2,1:3])

[[91 27 75]
 [ 9 93 33]
 [72 88 69]
 [87 15 36]
 [85 38 63]]
75
[88 69]


In [125]:
print(arr[arr>20])

[91 27 75 93 33 72 88 69 87 36 85 38 63]


In [153]:
print(arr[2][arr[2]>50])
print(arr[:,2])

[72 88 69]
[75 33 69 36 63]


#5.ndarray的运算

In [159]:
#算术运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
c = [1,2,3]
d = [4,5,6]
print(c+d)
for i in range(len(c)):
    d[i] = c[i]+d[i]

[5 7 9]
[1, 2, 3, 4, 5, 6]


In [162]:
#数组与标量的算数运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,1,2],[44,5,60],[27,58,9]])
print(a+b)
print(a+3)

[[ 5  3  5]
 [48 10 66]
 [34 66 18]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [164]:
#广播机制
#同一纬度：相同、1
a = np.array([[1,2,3]])#1*3
b = np.array([[4],[5],[6],[7],[8],[9]])
print(a+b)

[[ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]]


In [167]:
#矩阵运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,1,2],[44,5,60],[27,58,9]])
print(a*b)
print(a@b)
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

[[  4   2   6]
 [176  25 360]
 [189 464  81]]
[[173 185 149]
 [398 377 362]
 [623 569 575]]


#2.3numpy中的常用函数

##1.基本数学函数

In [171]:
#计算平方根
print(np.sqrt(9))
print(np.sqrt([1,2,3]))
arr = np.array([1,25,81])
print(arr)

3.0
[1.         1.41421356 1.73205081]
[ 1 25 81]


In [175]:
#计算指数e^
print(np.exp(1))

2.718281828459045


In [177]:
#计算自然对数 lnx
print(np.log(10))

2.302585092994046


In [181]:
#计算三角函数，正弦余弦
print(np.sin(np.pi))
print((np.cos(np.pi)))

1.2246467991473532e-16
-1.0


In [183]:
#计算绝对值
arr = np.array([1,-1,-200])
print(np.abs(arr))

[  1   1 200]


In [187]:
#计算a的b次幂
print(np.power(arr,3))

[       1       -1 -8000000]


In [194]:
#四舍五入
print(np.round([3.2,4.50,5.6]))


[3. 4. 6.]


In [197]:
#向上取整、向下取整
arr = np.array([1.1,3.2,5.6])
print(np.ceil(arr))
print(np.floor(arr))

[2. 4. 6.]
[1. 3. 5.]


In [201]:
#检测缺失值
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

#统计函数
##求和计算平均值、计算中位数、方差、查找最大值等

In [203]:
arr = np.random.randint(1,20,8)
print(arr)

[15 18  7 11  2 11 12  2]


In [205]:
#求和
print(np.sum(arr))

78


In [207]:
#计算平均值
print(np.mean(arr))

9.75


In [214]:
#计算中位数,奇数个中间的值，偶数中间两个数平均值
print(np.median([arr]))
print(np.median([1,2,3,5,4,8]))

11.0
3.5


In [223]:
#计算标准差、方差(1-1)^2+(2-2)^2...
print(np.var([1,2,3]))
print(np.var([1,2,3,4,5]))
print(np.std([1,2,3,4,5]))


0.6666666666666666
2.0
1.4142135623730951


In [224]:
#计算最大值、最小值
print(np.min([1,2,3,4,5]),np.argmax(arr))
print(np.max([1,2,3,4,5]))

1 1
5


In [232]:
#分位数
print(np.median([1,2,3,4,5]))
print(np.median([1,2,3,4]))
np.random.seed(0)
arr = np.random.randint(0,4,100)
print(np.median(arr))
print(np.percentile(arr,50))

3.0
2.5
2.0
2.0


In [234]:
#比较函数 比较大于小于等于，逻辑与或非、检查数组中知否有一个True，是否所有的都为True

In [246]:
#是否大于
print(np.greater([3,4,5,6,7],4))
print(np.less([3,4,5,6,7],4))
print(np.equal([3,4,5,6,7],4))
print(np.equal([3,4,5],[6,4,8]))

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False  True False]


In [257]:
#与或非
print(np.logical_and([3,4,5],[6,4,8]))
print(np.logical_or([0,0],[0,0]))
print(np.logical_not([0,0]))
#检查元素是否至少有一个元素为Yrue
print(np,any([0,0,0]))

[ True  True  True]
[False False]
[ True  True]
<module 'numpy' from 'D:\\ai-pm-journey\\.venv\\Lib\\site-packages\\numpy\\__init__.py'> False


In [261]:
#自定义条件
# print(np.where(条件，符合条件，不符合条件))
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,arr,0))

[1 2 0 0 0]


In [264]:
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,1,0))
score = np.random.randint(50,100,20)
print(score)
print(np.where(score>=60,'及格','不及格'))

[1 1 0 0 0]
[99 55 91 85 50 81 55 80 50 99 86 84 98 79 53 84 92 63 98 89]
['及格' '不及格' '及格' '及格' '不及格' '及格' '不及格' '及格' '不及格' '及格' '及格' '及格' '及格' '及格'
 '不及格' '及格' '及格' '及格' '及格' '及格']


In [266]:
print(np.where(
    score<60,'不及格',np.where(
        score<80,'良好','优秀'
    )
))

['优秀' '不及格' '优秀' '优秀' '不及格' '优秀' '不及格' '优秀' '不及格' '优秀' '优秀' '优秀' '优秀' '良好'
 '不及格' '优秀' '优秀' '良好' '优秀' '优秀']


In [271]:
#np.select
print(np.select([score>80,score>60,score==60,score<60],['优秀','良好','及格','不及格'],default='未知'))



['优秀' '不及格' '优秀' '优秀' '不及格' '优秀' '不及格' '良好' '不及格' '优秀' '优秀' '优秀' '优秀' '良好'
 '不及格' '优秀' '优秀' '良好' '优秀' '优秀']


In [277]:
#排序函数
arr = np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
arr.sort()
print(np.argsort(arr))
print(np.sort(arr))
print(np.argsort(arr))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [279]:
#去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [282]:
#数组拼接
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])
print(arr1+arr2)
print((np.concatenate([arr1,arr2])))

[ 5  7  9 11 13 15]
[1 2 3 4 5 6 4 5 6 7 8 9]


In [285]:
#数组切割
print(np.split(arr,[6,12,18]))

[array([10, 13, 22, 37, 40, 45], dtype=int32), array([47, 48, 59, 65, 66, 68], dtype=int32), array([68, 71, 84, 88, 88, 89], dtype=int32), array([89, 89], dtype=int32)]


In [289]:
#调整数组形状
print(np.reshape(arr,(5,4)))


[[10 13 22 37]
 [40 45 47 48]
 [59 65 66 68]
 [68 71 84 88]
 [88 89 89 89]]


题目一：温度数据分析
某城市一周的最高气温为【29，30，29，31，32，30，29】
计算平均气温、最高气温和最低气温
找出气温超过30°的天数

In [304]:
temps = np.array([29,30,29,31,32,30,29])
print('平均气温')
print('%.3f'%np.mean(temps))
print('最高气温')
print(np.max(temps))
print(np.min(temps))
print('气温超过三十度天数')
print(temps[temps>30])
print(len(temps[temps>30]))
arr = np.where(temps>30,temps,0)
target = 6
count = (arr > target).sum()
print(count)
print(np.where(temps>30,temps,0))
print(np.cumsum(np.where(temps>30,1,0))[-1])

平均气温
30.000
最高气温
32
29
气温超过三十度天数
[31 32]
2
2
[ 0  0  0 31 32  0  0]
2


题目二：学生成绩统计
某班级5名学生数学成绩为【85，90，78，92，88】
计算成绩的平均分、中位数和标准差
将成绩转换为百分制（假设满分为10）

In [314]:
score = np.array([85,90,78,92,88])
print(score)
print('平均分',np.mean(score))
print('中位数',np.median(score))
print('标准差:%.3f'%np.std(score))
print(score/10)

[85 90 78 92 88]
平均分 86.6
中位数 88.0
标准差:4.883
[8.5 9.  7.8 9.2 8.8]


题目 3：矩阵运算
给定矩阵 A = [[1, 2], [3, 4]] 和 B = [[5, 6], [7, 8]]。
计算 A + B 和 A * B（逐元素乘法）。
计算 A 和 B 的矩阵乘法（点积）。









In [317]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])
print(A*B)
print(A+B)
print(A@B)

[[ 4 10]
 [18 28]]
[[ 5  7]
 [ 9 11]]
[[16 19]
 [36 43]]


题目：随机数据生成
生成一个 (3, 4) 的随机整数数组，范围 [0, 10)。
计算每列的最大值和每行的最小值。
将数组中的所有奇数替换为 -1。

In [326]:
np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print(arr)
print('计算每列的最大值',np.max(arr,axis=0))#axis=0是列
print('计算每行的最小值',np.min(arr,axis=0))
print(np.where(arr%2==1,-1,arr))
#布尔索引
arr[:,0]=-1
print(arr)


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
计算每列的最大值 [7 9 7 6]
计算每行的最小值 [2 0 3 3]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0  3  3]
 [-1  9  3  5]
 [-1  4  7  6]]


题目 5：数组变形
创建一个 1 到 12 的一维数组，并转换为 (3, 4) 的二维数组。
- 计算每行的和与每列的平均值。
- 将数组展平为一维数组。

In [343]:
arr = np.arange(1,13)
print(arr)
arr = (np.reshape(arr,(3,4)))
print('每行的和',np.sum(arr,axis=1))
print('每列的平均值',np.average(arr,axis=0).astype(int))
print(np.reshape(arr,(12)))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
每行的和 [10 26 42]
每列的平均值 [5 6 7 8]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


题目 6：布尔索引
生成一个 (5, 5) 的随机数组，范围 [0, 20)。
- 找出数组中大于 10 的元素。
- 将所有大于 10 的元素替换为 0。

In [351]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr[arr>10])
arr[arr>10] = 0
print(arr)

[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


题目 7：统计函数应用
某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130, 140]。
- 计算销售额的总和、均值和方差。
- 找出销售额最高的月份和最低的月份。

In [357]:
money = np.array([120, 135, 110, 125, 130, 140])
print('销售额综合',np.sum(money),'万')
print('均价',np.mean(money))
print('方差',np.var(money))
print('最高的月份',np.argmax(money)+1)
print('最低的月份',np.argmin(money)+1)

销售额综合 760 万
均价 126.66666666666667
方差 97.22222222222223
最高的月份 6
最低的月份 3


题目 8：数组拼接
给定 A = [1, 2, 3] 和 B = [4, 5, 6]。
- 将 A 和 B 水平拼接为一个新数组。
- 将 A 和 B 垂直拼接为一个新数组。

In [362]:
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.concatenate([A,B])
print(C)
print(np.reshape(C,(2,3)))#把一维数组 C 重新排列成一个 2行×3列 的二维数组

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


题目 9：唯一值与排序
给定数组 [2, 1, 2, 3, 1, 4, 3]。
- 找出数组中的唯一值并排序。
- 计算每个唯一值出现的次数。

In [366]:
arr = np.array([2, 1, 2, 3, 1, 4, 3])
u_arr,counts = np.unique(arr,return_counts=True)
print(u_arr)
print(counts)


[1 2 3 4]
[2 2 2 1]
1
2
3
4


题目 20：综合应用
某商店 5 天的销售额（万元）和成本（万元）如下：
销售额：[20, 25, 22, 30, 28]
成本：[15, 18, 16, 22, 20]

- 计算每天的利润（销售额 - 成本）。
- 计算利润的平均值和标准差。
- 找出利润最高的天数。

In [374]:
money = np.array([20, 25, 22, 30, 28])
a = np.array([15, 18, 16, 22, 20])
print('每天的利润',money-a)
b = money-a
print('利润的平均值',np.mean(b))
print('利润的标准差',np.std(b))
print('利润最高的天数',len(b[b==np.max(b)]))

每天的利润 [5 7 6 8 8]
利润的平均值 6.8
利润的标准差 1.16619037896906
利润最高的天数 2


 什么情况下想到布尔索引
1. 筛选 / 找出满足条件的元素
大于、小于、等于、满足多个条件
arr [arr> 10] # 找出大于 10 的
arr [arr == 5] # 找出等于 5 的
arr [(arr>3) & (arr<8)] # 多个条件
2. 根据条件替换值
想把数组里满足条件的数改成别的值，比如：
大于 10 的改成 0
奇数改成 -1
低于平均值的改成平均值
arr [arr> 10] = 0 # 大于 10 的全部变 0
3. 统计满足条件的数量
有多少个数 > 5
有多少天利润 > 0
np.sum (arr> 5) # True=1, False=0, 求和就是数量
4. 获取满足条件的位置（索引）
np.where(arr == arr.max())
或者
arr == arr.max()